# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendation.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"t\n\x15RecommendationRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05grade\x18\x02 \x01(\x05\x12\x10\n\x08\x63hapters\x18\x03 \x03(\x05\x12\x14\n\x0c\x64ifficulties\x18\x04 \x03(\x05\x12\x13\n\x0bnumProblems\x18\x05 \x01(\x05\",\n\x16RecommendationResponse\x12\x12\n\nproblemIds\x18\x01 \x03(\x05\x32v\n\x0eRecommendation\x12\x64\n\x11GetRecommendation\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=40
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=156
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=158
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=202
  _globals['_RECOMMENDATION']._serialized_start=204
  _globals['_RECOMMENDATION']._serialized_end=322
# @@protoc_insertion_point(module_scope)
