"""create_theme_table

Revision ID: 659d9eb6c5fd
Revises: 3329ca1ea5a1
Create Date: 2024-02-02 00:17:57.161340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659d9eb6c5fd'
down_revision: Union[str, None] = '3329ca1ea5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
