"""add chapter_edition_relation

Revision ID: 98d646bd8cbb
Revises: 92ffeca107ae
Create Date: 2024-02-04 11:42:24.667638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d646bd8cbb'
down_revision: Union[str, None] = '92ffeca107ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
