"""fix

Revision ID: 9da814d458ec
Revises: 659157799fab
Create Date: 2024-02-07 01:06:08.639220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da814d458ec'
down_revision: Union[str, None] = '659157799fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_keyword_table')
    op.add_column('keywords_table', sa.Column('problem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'keywords_table', 'problems_table', ['problem_id'], ['id'])
    op.add_column('problems_table', sa.Column('nsrd_id', sa.Integer(), nullable=True))
    op.drop_constraint('problems_table_nsrd_key_fkey', 'problems_table', type_='foreignkey')
    op.create_foreign_key(None, 'problems_table', 'nsrd_table', ['nsrd_id'], ['id'])
    op.drop_column('problems_table', 'nsrd_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems_table', sa.Column('nsrd_key', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problems_table', type_='foreignkey')
    op.create_foreign_key('problems_table_nsrd_key_fkey', 'problems_table', 'nsrd_table', ['nsrd_key'], ['id'])
    op.drop_column('problems_table', 'nsrd_id')
    op.drop_constraint(None, 'keywords_table', type_='foreignkey')
    op.drop_column('keywords_table', 'problem_id')
    op.create_table('problem_keyword_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords_table.id'], name='problem_keyword_table_keyword_id_fkey'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems_table.id'], name='problem_keyword_table_problem_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='problem_keyword_table_pkey')
    )
    # ### end Alembic commands ###
