// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

#include "recommendation.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace recommendation {

inline constexpr RecommendationResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : problemids_{},
        _problemids_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecommendationResponse::RecommendationResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RecommendationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecommendationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecommendationResponseDefaultTypeInternal() {}
  union {
    RecommendationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecommendationResponseDefaultTypeInternal _RecommendationResponse_default_instance_;

inline constexpr RecommendationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : chapters_{},
        _chapters_cached_byte_size_{0},
        difficulties_{},
        _difficulties_cached_byte_size_{0},
        version_{0},
        grade_{0},
        numproblems_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecommendationRequest::RecommendationRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RecommendationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecommendationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecommendationRequestDefaultTypeInternal() {}
  union {
    RecommendationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecommendationRequestDefaultTypeInternal _RecommendationRequest_default_instance_;
}  // namespace recommendation
static ::_pb::Metadata file_level_metadata_recommendation_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_recommendation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_recommendation_2eproto = nullptr;
const ::uint32_t TableStruct_recommendation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationRequest, _impl_.version_),
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationRequest, _impl_.grade_),
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationRequest, _impl_.chapters_),
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationRequest, _impl_.difficulties_),
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationRequest, _impl_.numproblems_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::recommendation::RecommendationResponse, _impl_.problemids_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::recommendation::RecommendationRequest)},
        {13, -1, -1, sizeof(::recommendation::RecommendationResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::recommendation::_RecommendationRequest_default_instance_._instance,
    &::recommendation::_RecommendationResponse_default_instance_._instance,
};
const char descriptor_table_protodef_recommendation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024recommendation.proto\022\016recommendation\"t"
    "\n\025RecommendationRequest\022\017\n\007version\030\001 \001(\005"
    "\022\r\n\005grade\030\002 \001(\005\022\020\n\010chapters\030\003 \003(\005\022\024\n\014dif"
    "ficulties\030\004 \003(\005\022\023\n\013numProblems\030\005 \001(\005\",\n\026"
    "RecommendationResponse\022\022\n\nproblemIds\030\001 \003"
    "(\0052v\n\016Recommendation\022d\n\021GetRecommendatio"
    "n\022%.recommendation.RecommendationRequest"
    "\032&.recommendation.RecommendationResponse"
    "\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_recommendation_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_recommendation_2eproto = {
    false,
    false,
    330,
    descriptor_table_protodef_recommendation_2eproto,
    "recommendation.proto",
    &descriptor_table_recommendation_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_recommendation_2eproto::offsets,
    file_level_metadata_recommendation_2eproto,
    file_level_enum_descriptors_recommendation_2eproto,
    file_level_service_descriptors_recommendation_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_recommendation_2eproto_getter() {
  return &descriptor_table_recommendation_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_recommendation_2eproto(&descriptor_table_recommendation_2eproto);
namespace recommendation {
// ===================================================================

class RecommendationRequest::_Internal {
 public:
};

RecommendationRequest::RecommendationRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recommendation.RecommendationRequest)
}
inline PROTOBUF_NDEBUG_INLINE RecommendationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : chapters_{visibility, arena, from.chapters_},
        _chapters_cached_byte_size_{0},
        difficulties_{visibility, arena, from.difficulties_},
        _difficulties_cached_byte_size_{0},
        _cached_size_{0} {}

RecommendationRequest::RecommendationRequest(
    ::google::protobuf::Arena* arena,
    const RecommendationRequest& from)
    : ::google::protobuf::Message(arena) {
  RecommendationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, version_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, version_),
           offsetof(Impl_, numproblems_) -
               offsetof(Impl_, version_) +
               sizeof(Impl_::numproblems_));

  // @@protoc_insertion_point(copy_constructor:recommendation.RecommendationRequest)
}
inline PROTOBUF_NDEBUG_INLINE RecommendationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : chapters_{visibility, arena},
        _chapters_cached_byte_size_{0},
        difficulties_{visibility, arena},
        _difficulties_cached_byte_size_{0},
        _cached_size_{0} {}

inline void RecommendationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, version_),
           0,
           offsetof(Impl_, numproblems_) -
               offsetof(Impl_, version_) +
               sizeof(Impl_::numproblems_));
}
RecommendationRequest::~RecommendationRequest() {
  // @@protoc_insertion_point(destructor:recommendation.RecommendationRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecommendationRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RecommendationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:recommendation.RecommendationRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chapters_.Clear();
  _impl_.difficulties_.Clear();
  ::memset(&_impl_.version_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.numproblems_) -
      reinterpret_cast<char*>(&_impl_.version_)) + sizeof(_impl_.numproblems_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RecommendationRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> RecommendationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RecommendationRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RecommendationRequest, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.version_)}},
    // int32 grade = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RecommendationRequest, _impl_.grade_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.grade_)}},
    // repeated int32 chapters = 3;
    {::_pbi::TcParser::FastV32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.chapters_)}},
    // repeated int32 difficulties = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.difficulties_)}},
    // int32 numProblems = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RecommendationRequest, _impl_.numproblems_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.numproblems_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 version = 1;
    {PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 grade = 2;
    {PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.grade_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated int32 chapters = 3;
    {PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.chapters_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated int32 difficulties = 4;
    {PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.difficulties_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // int32 numProblems = 5;
    {PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.numproblems_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RecommendationRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recommendation.RecommendationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_version(), target);
  }

  // int32 grade = 2;
  if (this->_internal_grade() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_grade(), target);
  }

  // repeated int32 chapters = 3;
  {
    int byte_size = _impl_._chapters_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          3, _internal_chapters(), byte_size, target);
    }
  }

  // repeated int32 difficulties = 4;
  {
    int byte_size = _impl_._difficulties_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          4, _internal_difficulties(), byte_size, target);
    }
  }

  // int32 numProblems = 5;
  if (this->_internal_numproblems() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_numproblems(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recommendation.RecommendationRequest)
  return target;
}

::size_t RecommendationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recommendation.RecommendationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 chapters = 3;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_chapters())
    ;
    _impl_._chapters_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated int32 difficulties = 4;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_difficulties())
    ;
    _impl_._difficulties_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // int32 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_version());
  }

  // int32 grade = 2;
  if (this->_internal_grade() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_grade());
  }

  // int32 numProblems = 5;
  if (this->_internal_numproblems() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_numproblems());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RecommendationRequest::_class_data_ = {
    RecommendationRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RecommendationRequest::GetClassData() const {
  return &_class_data_;
}

void RecommendationRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RecommendationRequest*>(&to_msg);
  auto& from = static_cast<const RecommendationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recommendation.RecommendationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_chapters()->MergeFrom(from._internal_chapters());
  _this->_internal_mutable_difficulties()->MergeFrom(from._internal_difficulties());
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  if (from._internal_grade() != 0) {
    _this->_internal_set_grade(from._internal_grade());
  }
  if (from._internal_numproblems() != 0) {
    _this->_internal_set_numproblems(from._internal_numproblems());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecommendationRequest::CopyFrom(const RecommendationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recommendation.RecommendationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RecommendationRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RecommendationRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RecommendationRequest::InternalSwap(RecommendationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.chapters_.InternalSwap(&other->_impl_.chapters_);
  _impl_.difficulties_.InternalSwap(&other->_impl_.difficulties_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.numproblems_)
      + sizeof(RecommendationRequest::_impl_.numproblems_)
      - PROTOBUF_FIELD_OFFSET(RecommendationRequest, _impl_.version_)>(
          reinterpret_cast<char*>(&_impl_.version_),
          reinterpret_cast<char*>(&other->_impl_.version_));
}

::google::protobuf::Metadata RecommendationRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_recommendation_2eproto_getter, &descriptor_table_recommendation_2eproto_once,
      file_level_metadata_recommendation_2eproto[0]);
}
// ===================================================================

class RecommendationResponse::_Internal {
 public:
};

RecommendationResponse::RecommendationResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recommendation.RecommendationResponse)
}
inline PROTOBUF_NDEBUG_INLINE RecommendationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : problemids_{visibility, arena, from.problemids_},
        _problemids_cached_byte_size_{0},
        _cached_size_{0} {}

RecommendationResponse::RecommendationResponse(
    ::google::protobuf::Arena* arena,
    const RecommendationResponse& from)
    : ::google::protobuf::Message(arena) {
  RecommendationResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:recommendation.RecommendationResponse)
}
inline PROTOBUF_NDEBUG_INLINE RecommendationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : problemids_{visibility, arena},
        _problemids_cached_byte_size_{0},
        _cached_size_{0} {}

inline void RecommendationResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecommendationResponse::~RecommendationResponse() {
  // @@protoc_insertion_point(destructor:recommendation.RecommendationResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecommendationResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RecommendationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:recommendation.RecommendationResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.problemids_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RecommendationResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RecommendationResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RecommendationResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated int32 problemIds = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecommendationResponse, _impl_.problemids_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 problemIds = 1;
    {PROTOBUF_FIELD_OFFSET(RecommendationResponse, _impl_.problemids_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RecommendationResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recommendation.RecommendationResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated int32 problemIds = 1;
  {
    int byte_size = _impl_._problemids_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_problemids(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recommendation.RecommendationResponse)
  return target;
}

::size_t RecommendationResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recommendation.RecommendationResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 problemIds = 1;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_problemids())
    ;
    _impl_._problemids_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RecommendationResponse::_class_data_ = {
    RecommendationResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RecommendationResponse::GetClassData() const {
  return &_class_data_;
}

void RecommendationResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RecommendationResponse*>(&to_msg);
  auto& from = static_cast<const RecommendationResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recommendation.RecommendationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_problemids()->MergeFrom(from._internal_problemids());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecommendationResponse::CopyFrom(const RecommendationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recommendation.RecommendationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RecommendationResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RecommendationResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RecommendationResponse::InternalSwap(RecommendationResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.problemids_.InternalSwap(&other->_impl_.problemids_);
}

::google::protobuf::Metadata RecommendationResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_recommendation_2eproto_getter, &descriptor_table_recommendation_2eproto_once,
      file_level_metadata_recommendation_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace recommendation
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
