# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recommendation_pb2 as recommendation__pb2


class RecommendationStub(object):
    """The recommendation service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendation = channel.unary_unary(
                '/recommendation.Recommendation/GetRecommendation',
                request_serializer=recommendation__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=recommendation__pb2.RecommendationResponse.FromString,
                )


class RecommendationServicer(object):
    """The recommendation service definition
    """

    def GetRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendation,
                    request_deserializer=recommendation__pb2.RecommendationRequest.FromString,
                    response_serializer=recommendation__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.Recommendation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recommendation(object):
    """The recommendation service definition
    """

    @staticmethod
    def GetRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recommendation.Recommendation/GetRecommendation',
            recommendation__pb2.RecommendationRequest.SerializeToString,
            recommendation__pb2.RecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
