// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: recommendation.proto

#include "recommendation.pb.h"
#include "recommendation.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace recommendation {

static const char* Recommendation_method_names[] = {
  "/recommendation.Recommendation/GetRecommendation",
};

std::unique_ptr< Recommendation::Stub> Recommendation::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Recommendation::Stub> stub(new Recommendation::Stub(channel, options));
  return stub;
}

Recommendation::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetRecommendation_(Recommendation_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Recommendation::Stub::GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::recommendation::RecommendationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRecommendation_, context, request, response);
}

void Recommendation::Stub::async::GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRecommendation_, context, request, response, std::move(f));
}

void Recommendation::Stub::async::GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRecommendation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>* Recommendation::Stub::PrepareAsyncGetRecommendationRaw(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::recommendation::RecommendationResponse, ::recommendation::RecommendationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRecommendation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>* Recommendation::Stub::AsyncGetRecommendationRaw(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRecommendationRaw(context, request, cq);
  result->StartCall();
  return result;
}

Recommendation::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recommendation_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recommendation::Service, ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recommendation::Service* service,
             ::grpc::ServerContext* ctx,
             const ::recommendation::RecommendationRequest* req,
             ::recommendation::RecommendationResponse* resp) {
               return service->GetRecommendation(ctx, req, resp);
             }, this)));
}

Recommendation::Service::~Service() {
}

::grpc::Status Recommendation::Service::GetRecommendation(::grpc::ServerContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace recommendation

