// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: recommendation.proto
#ifndef GRPC_recommendation_2eproto__INCLUDED
#define GRPC_recommendation_2eproto__INCLUDED

#include "recommendation.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace recommendation {

// The recommendation service definition
class Recommendation final {
 public:
  static constexpr char const* service_full_name() {
    return "recommendation.Recommendation";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::recommendation::RecommendationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recommendation::RecommendationResponse>> AsyncGetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recommendation::RecommendationResponse>>(AsyncGetRecommendationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recommendation::RecommendationResponse>> PrepareAsyncGetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recommendation::RecommendationResponse>>(PrepareAsyncGetRecommendationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::recommendation::RecommendationResponse>* AsyncGetRecommendationRaw(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::recommendation::RecommendationResponse>* PrepareAsyncGetRecommendationRaw(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::recommendation::RecommendationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>> AsyncGetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>>(AsyncGetRecommendationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>> PrepareAsyncGetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>>(PrepareAsyncGetRecommendationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRecommendation(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>* AsyncGetRecommendationRaw(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::recommendation::RecommendationResponse>* PrepareAsyncGetRecommendationRaw(::grpc::ClientContext* context, const ::recommendation::RecommendationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetRecommendation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetRecommendation(::grpc::ServerContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRecommendation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRecommendation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetRecommendation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecommendation(::grpc::ServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRecommendation(::grpc::ServerContext* context, ::recommendation::RecommendationRequest* request, ::grpc::ServerAsyncResponseWriter< ::recommendation::RecommendationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetRecommendation<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetRecommendation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRecommendation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::recommendation::RecommendationRequest* request, ::recommendation::RecommendationResponse* response) { return this->GetRecommendation(context, request, response); }));}
    void SetMessageAllocatorFor_GetRecommendation(
        ::grpc::MessageAllocator< ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRecommendation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecommendation(::grpc::ServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRecommendation(
      ::grpc::CallbackServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetRecommendation<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetRecommendation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRecommendation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetRecommendation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecommendation(::grpc::ServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRecommendation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRecommendation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetRecommendation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecommendation(::grpc::ServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRecommendation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRecommendation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRecommendation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRecommendation(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRecommendation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecommendation(::grpc::ServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRecommendation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRecommendation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRecommendation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::recommendation::RecommendationRequest, ::recommendation::RecommendationResponse>* streamer) {
                       return this->StreamedGetRecommendation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRecommendation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRecommendation(::grpc::ServerContext* /*context*/, const ::recommendation::RecommendationRequest* /*request*/, ::recommendation::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRecommendation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::recommendation::RecommendationRequest,::recommendation::RecommendationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetRecommendation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetRecommendation<Service > StreamedService;
};

}  // namespace recommendation


#endif  // GRPC_recommendation_2eproto__INCLUDED
