"""fix problem

Revision ID: 609ae5cde296
Revises: 3cf8b3b912c0
Create Date: 2024-02-09 00:34:45.074626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609ae5cde296'
down_revision: Union[str, None] = '3cf8b3b912c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems_table', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problems_table', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('problems_table', 'chapter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems_table', sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problems_table', type_='foreignkey')
    op.drop_column('problems_table', 'chapter_id')
    # ### end Alembic commands ###
