"""create_nsrd

Revision ID: 659157799fab
Revises: 52123e9a4c91
Create Date: 2024-02-06 17:49:50.715735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659157799fab'
down_revision: Union[str, None] = '52123e9a4c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nsrd_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nsrd_table_category'), 'nsrd_table', ['category'], unique=False)
    op.create_index(op.f('ix_nsrd_table_id'), 'nsrd_table', ['id'], unique=False)
    op.add_column('problems_table', sa.Column('nsrd_key', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problems_table', 'nsrd_table', ['nsrd_key'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems_table', type_='foreignkey')
    op.drop_column('problems_table', 'nsrd_key')
    op.drop_index(op.f('ix_nsrd_table_id'), table_name='nsrd_table')
    op.drop_index(op.f('ix_nsrd_table_category'), table_name='nsrd_table')
    op.drop_table('nsrd_table')
    # ### end Alembic commands ###
