"""create_tables

Revision ID: 6626aa2d8866
Revises: 659d9eb6c5fd
Create Date: 2024-02-02 11:47:15.235058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6626aa2d8866'
down_revision: Union[str, None] = '659d9eb6c5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nasd', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edition_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.Column('grade_number', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_keyword_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_theme_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems_table.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='theme_pkey')
    )
    op.drop_table('problem_theme_table')
    op.drop_table('problem_keyword_table')
    op.drop_table('problems_table')
    op.drop_table('edition_chapters')
    op.drop_table('themes_table')
    op.drop_table('program_table')
    op.drop_table('keywords_table')
    op.drop_table('editions')
    op.drop_table('chapters')
    # ### end Alembic commands ###
