"""add id autoIncrement

Revision ID: 92ffeca107ae
Revises: 6626aa2d8866
Create Date: 2024-02-02 13:30:29.993518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ffeca107ae'
down_revision: Union[str, None] = '6626aa2d8866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_edition_chapters_id'), 'edition_chapters', ['id'], unique=False)
    op.create_index(op.f('ix_editions_id'), 'editions', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_table_id'), 'keywords_table', ['id'], unique=False)
    op.add_column('problem_keyword_table', sa.Column('keyword_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem_keyword_table', 'keywords_table', ['keyword_id'], ['id'])
    op.drop_column('problem_keyword_table', 'keyword')
    op.create_index(op.f('ix_problems_table_id'), 'problems_table', ['id'], unique=False)
    op.create_index(op.f('ix_program_table_id'), 'program_table', ['id'], unique=False)
    op.create_index(op.f('ix_themes_table_id'), 'themes_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_table_id'), table_name='themes_table')
    op.drop_index(op.f('ix_program_table_id'), table_name='program_table')
    op.drop_index(op.f('ix_problems_table_id'), table_name='problems_table')
    op.add_column('problem_keyword_table', sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problem_keyword_table', type_='foreignkey')
    op.drop_column('problem_keyword_table', 'keyword_id')
    op.drop_index(op.f('ix_keywords_table_id'), table_name='keywords_table')
    op.drop_index(op.f('ix_editions_id'), table_name='editions')
    op.drop_index(op.f('ix_edition_chapters_id'), table_name='edition_chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    # ### end Alembic commands ###
