"""Drop foreign key constraint from problems_table

Revision ID: 9cbd1e933853
Revises: 5b40f58bd2ec
Create Date: 2024-10-04 03:19:43.653360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbd1e933853'
down_revision: Union[str, None] = '5b40f58bd2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems_table', sa.Column('n_score', sa.Integer(), nullable=True))
    op.add_column('problems_table', sa.Column('s_score', sa.Integer(), nullable=True))
    op.add_column('problems_table', sa.Column('r_score', sa.Integer(), nullable=True))
    op.add_column('problems_table', sa.Column('d_score', sa.Integer(), nullable=True))
    op.drop_constraint('problems_table_nsrd_id_fkey', 'problems_table', type_='foreignkey')
    op.drop_column('problems_table', 'nsrd_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems_table', sa.Column('nsrd_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('problems_table_nsrd_id_fkey', 'problems_table', 'nsrd_table', ['nsrd_id'], ['id'])
    op.drop_column('problems_table', 'd_score')
    op.drop_column('problems_table', 'r_score')
    op.drop_column('problems_table', 's_score')
    op.drop_column('problems_table', 'n_score')
    # ### end Alembic commands ###
